import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlobalProvider from "./provider";
import GlobalHeader from "@/components/Header";
import GlobalFooter from "@/components/Footer";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "lx-next-starter",
  description: "Generated by create next app",
};
/**
 * 默认布局
 * @param param0
 * @returns
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <AntdRegistry>
            <GlobalHeader />
            {children}
            <GlobalFooter />
          </AntdRegistry>
        </GlobalProvider>
      </body>
    </html>
  );
}
