import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlobalProvider from "./provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import { SITE_CONFIG } from "@/config/site";
import { LAYOUT_TYPE } from "@/constants";
import TopLayout from "@/layouts/top";
import SideLayout from "@/layouts/side";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "lx-next-starter",
  description: "Generated by create next app",
};
/**
 * 默认布局
 * @param param0
 * @returns
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <AntdRegistry>
            {SITE_CONFIG.layout === LAYOUT_TYPE.TOP ? (
              <TopLayout children={children} />
            ) : (
              <SideLayout children={children} />
            )}
          </AntdRegistry>
        </GlobalProvider>
      </body>
    </html>
  );
}
